dist: bionic
language: minimal

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - "sudo apt-get install -y -qq \
    sshpass"

before_script:
  - make docker-image

script:
  - make docker-build

after_success:
  - sha256sum koncept.pdf
  - sshpass -e scp koncept.pdf ${FTP_USER}@${FTP_SERVER}:${FTP_FOLDER}koncept-pdf/koncept.$(cat VERSION.txt)+b$(printf "%04d" "${TRAVIS_BUILD_NUMBER}").${TRAVIS_COMMIT:0:7}.pdf
  - sshpass -e ssh ${FTP_USER}@${FTP_SERVER} ln -sf \~/${FTP_FOLDER}koncept-pdf/koncept.$(cat VERSION.txt)+b$(printf "%04d" "${TRAVIS_BUILD_NUMBER}").${TRAVIS_COMMIT:0:7}.pdf \~/${FTP_FOLDER}koncept-pdf/koncept.pdf

addons:
  ssh_known_hosts:
  - akademin.ssa.se
  - 89.221.240.114
