language: generic

before_install:
  - |-
    echo "\$TRAVIS_EVENT_TYPE: $TRAVIS_EVENT_TYPE"
  - sudo apt-get -qq update
  - "sudo apt-get install -y -qq \
    texlive \
    texlive-lang-european \
    texlive-latex-extra \
    texlive-fonts-extra \
    texlive-pictures \
    texlive-math-extra \
    texlive-xetex \
    sshpass"

script:
  - make koncept.pdf

after_success:
  - sha256sum koncept.pdf
  - sshpass -e scp koncept.pdf ${FTP_USER}@${FTP_SERVER}:${FTP_FOLDER}koncept-pdf/koncept.$(cat VERSION.txt)+b$(printf "%04d" "${TRAVIS_BUILD_NUMBER}").${TRAVIS_COMMIT:0:7}.pdf
  - sshpass -e ssh ${FTP_USER}@${FTP_SERVER} ln -sf \~/${FTP_FOLDER}koncept-pdf/koncept.$(cat VERSION.txt)+b$(printf "%04d" "${TRAVIS_BUILD_NUMBER}").${TRAVIS_COMMIT:0:7}.pdf \~/${FTP_FOLDER}koncept-pdf/koncept.pdf

deploy:
  provider: releases
  api_key:
    secure: [YOUR KEY]
  file:
    koncept.pdf
  skip_cleanup: true
  on:
    tags: true

addons:
  ssh_known_hosts:
  - akademin.ssa.se
  - 89.221.240.114
