before_install:
  - sudo apt-get -qq update
  - "sudo apt-get install -y -qq texlive texlive-lang-european texlive-latex-extra texlive-fonts-extra texlive-pictures texlive-math-extra texlive-xetex"

script:
  - make koncept.pdf

after_success:
  - "curl --ftp-create-dirs --upload-file koncept.pdf --user $FTP_USER:$FTP_PASSWORD ftp://$FTP_SERVER/${FTP_FOLDER}koncept.$TRAVIS_COMMIT.pdf"

deploy:
  provider: releases
  api_key:
    secure: [YOUR KEY]
  file:
    koncept.pdf
  skip_cleanup: true
  on:
    tags: true
